spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/lowcode?sslmode=disable&stringtype=unspecified
spring.datasource.username=lowcode
spring.datasource.password=lowcode
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
